### ISSUE TITLE
documentation issue

### ISSUE THREAD

**Issue by andrei9669** [kyleshevlin/eslint-plugin-use-encapsulation#2]
in the README, the plugin is added as `"@kyleshevlin"` but instead should be `"use-encapsulation"`

also, quick question, why the split happened, as in, why create a separate repo for the encapsulation plugin?

**Comment by kyleshevlin** [comment]
Fixed with 4f215d1

Answer is simple, people didn't like installing my personal ESLint package into their product. Moving the `use-encapsulation` rule out to its own plugin made people happy. I think people found it particularly odd to see `@kyleshevlin` in work projects.
