### ISSUE TITLE
[docs]: How to use in flat config?

### ISSUE THREAD

**Issue by rakleed** [kyleshevlin/eslint-plugin-use-encapsulation#7]
Please add to [README](https://github.com/kyleshevlin/eslint-plugin-use-encapsulation/blob/main/README.md) information about how to use your plugin in flat config. Now it has information only about usage with eslintrc which is deprecated in ESLint 9.

**Comment by kyleshevlin** [comment]
Any chance you'd want to make a PR for it? I've never configured anything for ESLint v9 yet.

**Comment by manavm1990** [comment]
> Any chance you'd want to make a PR for it? I've never configured anything for ESLint v9 yet.

~~#8 @kyleshevlin~~

**Update:** #9
